### ISSUE TITLE
[Fedora 38] Github Desktop window border looking weird

### ISSUE THREAD

**Issue by fr3nchalp4a** [vinceliuice/WhiteSur-gtk-theme#851] opened 2023-04-19 18:08 UTC
**Completely uptodate Fedora 38 with latest version of the theme (cloned from Github, installed with libadwaita fix)**
![image](https://user-images.githubusercontent.com/68474172/233162588-ac98e8a1-a34a-4466-9a10-5dcd7786c144.png)

**Comment by cesaraquino** [comment] 2023-04-19 18:45
Hi, I also have Fedora 38 and Gnome 44 (with Xorg) and the same thing happens to me with HandBrake, VLC, About Firefox, GIMP, Inkscape, etc. windows. Only some programs allow to place the title bar buttons on the left side of the window.

![whitesur theme apps](https://user-images.githubusercontent.com/4138916/233169902-9af4b4dd-6e3a-4d3c-a124-8d1e454ef5f9.png)

**Comment by fr3nchalp4a** [comment] 2023-04-20 07:01
Oh, it disappeared after disabling all themes + extensions, doing alt+f2 r to reload Gnome (Wayland users, you must logout) and then reactivating all the extensions and the theme, then re-reloading to apply all the changes.

I leave this open if the problem reappears.

**Comment by rcarmo** [comment] 2023-04-20 18:45
I have that issue on all the machines I run X instead of Wayland.

**Comment by cesaraquino** [comment] 2023-04-20 19:08
Hi, it was fixed a bit by reloading GNOME Shell with Alt + F2 r, but like @rcarmo, the non-GTK apps buttons are not fully placed on the left side of the window, although I don't see it as a big problem, I guess it will be fixed in future updates.

**Comment by rcarmo** [comment] 2023-04-20 19:14
It seems like such a conceptually easy thing to fix...

I find it visually annoying, and am poring through the `.scss` files to see if I can shift the buttons and increase the title bar just a bit - but haven't been able to figure out where those are defined...

**Comment by cesaraquino** [comment] 2023-04-21 23:12
I see that the problem is not completely solved. At each system restart the title bar buttons of the non-GTK apps return to the right side of the window.

**Comment by vinceliuice** [comment] 2023-04-24 06:26
Fixed now!

**Closed by vinceliuice** 2023-04-24 06:26 UTC
Labels: bug
