### ISSUE TITLE
Gnome 45 window oddities

### ISSUE THREAD

**Issue by quantum-quirks** [vinceliuice/WhiteSur-gtk-theme#939] opened 2023-09-25 13:57 UTC
Nautilus title bar acting funny
![Screenshot from 2023-09-25 09-52-11](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34297473/3140ac21-2583-46ea-be5b-6aeda7213db0)

Gnome settings app title bar acting funny
![Screenshot from 2023-09-25 09-51-53](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34297473/aedfd8d8-eb30-4781-9668-de0764e38621)

![Screenshot from 2023-09-25 09-51-25](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34297473/306a23d5-28a3-425e-b8ca-176bb8f079d3)

Nautilus displaying a transparent window when it encounters an empty folder

**Comment by RyzenDew** [comment] 2023-09-25 20:56
Duplicate of #933

**Comment by vinceliuice** [comment] 2023-10-12 22:37
Fixed now

**Closed by vinceliuice** 2023-10-12 22:37 UTC
Labels: bug
