### ISSUE TITLE
An error occurred in package().

### ISSUE THREAD

**Issue by AAlieZZ** [vinceliuice/WhiteSur-gtk-theme#730] opened 2022-11-12 15:51 UTC
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> Error: Undefined variable: "$base".
  >>>         on line 248:23 of src/sass/gtk/apps/_misc.scss
  >>>         from line 26:9 of src/sass/gtk/_apps-3.0.scss
  >>>         from line 7:9 of src/main/gtk-3.0/gtk-Dark.scss
  >>> >>     background-color: $base;
  >>> 
  >>>    ----------------------^
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> sassc ${SASSC_OPT} "${THEME_SRC_DIR}/main/gtk-3.0/gtk${color}.scss" "${TMP_DIR_T}/gtk.css"
  TRACE  :
    >>> signal_error
    >>> install_theemy
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : rolling;arch
  SUDO   : no
  GNOME  : none
  REPO   : 2022-11-12T23:34:05+0800

**Comment by austinjonestucker** [comment] 2022-11-12 15:53
I believe this is being caused by this commit -> https://github.com/vinceliuice/WhiteSur-gtk-theme/commit/9397a3492213d69f26695ecd21c1ee2350a7e46b. The variable $base should be $base_color.

**Comment by Neelakash-gituser** [comment] 2022-11-12 16:11
Facing the exact same issue .

**Comment by vinceliuice** [comment] 2022-11-12 16:39
Fixed now

**Closed by vinceliuice** 2022-11-12 16:39 UTC
Labels: bug
